version: '3.8'

services:
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"

  celery:
    build: .
#    depends_on:
#      - redis
    command: celery -A src.worker:app worker -l info

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
#      - redis
      - postgres
    command: uvicorn main:app --reload
    ports:
      - "8000:8000"

volumes:
  postgres_data: