version: '3.8'

networks:
  dev:

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - dev

  redis:
    image: redis:7.0.5-alpine
    volumes:
      - ./redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - dev

  worker:
    build:
      context: .
    command:
      - taskiq
      - worker
      - main:broker
      - main
    networks:
      - dev

  scheduler:
    build:
      context: .
    command:
      - taskiq
      - scheduler
      - main:scheduler
    networks:
      - dev

  web:
    build:
      context: .
    command:
      - uvicorn
      - main:app
      - --host
      - 127.0.0.1
      - --port
      - "8000"
      - --reload
    networks:
      - dev

volumes:
  postgres_data: