"""add tables

Revision ID: d2dc5ff7be81
Revises: 652d558eef02
Create Date: 2024-07-24 21:44:11.920121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2dc5ff7be81'
down_revision: Union[str, None] = '652d558eef02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horoscope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('zodiac_sign', sa.Enum('ARIES', 'TAURUS', 'GEMINI', 'CANCER', 'LEO', 'VIRGO', 'LIBRA', 'SCORPIO', 'SAGITTARIUS', 'CAPRICORN', 'AQUARIUS', 'PISCES', name='zodiacsigns'), nullable=False),
    sa.Column('horoscope_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horoscope')
    # ### end Alembic commands ###
